export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_HISTORY = 'SET_USER_HISTORY';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const GET_ADMIN_ROOMS = 'GET_ADMIN_ROOMS';
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';